name: 🤖 Update Chuck Norris Joke

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7:00 UTC
  workflow_dispatch: # Manual trigger option
  push:
    branches: 
       - master
  pull_request:

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Get Chuck Norris Joke
        id: joke
        run: |
          joke=$(curl -s https://api.chucknorris.io/jokes/random?category=dev | jq -r '.value')
          echo "joke=$joke" >> $GITHUB_OUTPUT

      - name: Replace Joke in README
        run: |
          joke="${{ steps.joke.outputs.joke }}"
          # Escape slashes
          joke_escaped=$(echo "$joke" | sed 's/[&/\]/\\&/g')
          sed -i "/<!-- CHUCK_NORRIS_JOKE_START -->/,/<!-- CHUCK_NORRIS_JOKE_END -->/c\\<!-- CHUCK_NORRIS_JOKE_START -->\n🦾 $joke_escaped\n<!-- CHUCK_NORRIS_JOKE_END -->" README.md

      - name: Add s to yes
        run: |
          sed -i -E 's/(yes+)\s*$/\1s/' README.md
          

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull latest changes
        run: |
          git pull origin master --rebase

      - name: Commit changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "🤖 Update Chuck Norris joke"

      - name: Push changes
        run: |
          git push origin master

        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


