name: 🤖 Update Chuck Norris Joke

on:
  schedule:
    - cron: "0 7 * * *"  # Runs every day at 7:00 UTC
  workflow_dispatch: # Manual trigger option
  push:
    branches: 
       - master
  pull_request:

jobs:
  update-joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v1

      - name: Get Chuck Norris Joke
        id: joke
        run: |
          joke=$(curl -s https://api.chucknorris.io/jokes/random?category=dev | jq -r '.value')
          echo "joke=$joke" >> $GITHUB_OUTPUT

      - name: Replace Joke in README
        run: |
          joke="${{ steps.joke.outputs.joke }}"
          # Escape slashes
          joke_escaped=$(echo "$joke" | sed 's/[&/\]/\\&/g')
          sed -i "/<!-- CHUCK_NORRIS_JOKE_START -->/,/<!-- CHUCK_NORRIS_JOKE_END -->/c\\<!-- CHUCK_NORRIS_JOKE_START -->\n🦾 $joke_escaped\n<!-- CHUCK_NORRIS_JOKE_END -->" README.md

      #- name: Add s to yes
      #  run: |
      #    

      - name: Add, commit, and push
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      #- name: Commit and Push if Changed
      #  env:
      #    GH_PAT: ${{ secrets.GH_PAT }}
      #  run: |
      #    git config --global user.name "Ivailo Iliev (Bot)"
      #    git config --global user.email "ivailo@example.com"
      #    git remote set-url origin https://x-access-token:$GH_PAT@github.com/${{ github.repository }}
      #    git add README.md
      #    git diff --cached --quiet || git commit -m "🤖 Update Chuck Norris joke"
      #    git push


